name: Pipeline CI

on:
  push:
    branches: [ "pedro-test" ]
  pull_request:
    branches: [ "pedro-test" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      
    - name: Build the project
      run: npm run build

    - name: Upload node_modules
      uses: actions/upload-artifact@v2
      with:
        name: node-modules
        path: node_modules/
        
    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download node_modules
      uses: actions/download-artifact@v2
      with:
        name: node-modules

    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: dist

    - name: Run the tests
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Download node_modules
      uses: actions/download-artifact@v2
      with:
        name: node-modules

    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: dist
      
    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
