name: Pipeline CI

on:
  push:
    branches: [ "pedro-test" ]
  pull_request:
    branches: [ "pedro-test" ]

jobs:

  checkout: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List directories for debug
      run: |
        pwd
        ls -al

  setup:
    runs-on: ubuntu-latest
    needs: checkout
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
      
    - name: Build the project
      run: npm run build

    - name: Cache node modules and build
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: nodeModulesAndBuild
        path: |
          node_modules/
          dist/

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Download cached node modules and build
      uses: actions/download-artifact@v2
      with:
        name: nodeModulesAndBuild

    - name: Run the tests
      run: npm test
      working-directory: nodeModulesAndBuild

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Download cached node modules and build
      uses: actions/download-artifact@v2
      with:
        name: nodeModulesAndBuild

    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      working-directory: nodeModulesAndBuild
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
