name: Pipeline CI

on:
  push:
    branches: [ "pedro-test" ]
  pull_request:
    branches: [ "pedro-test" ]

jobs:
  checkout: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List directories for debug
      run: |
        pwd
        ls -al

  setup:
    runs-on: ubuntu-latest
    needs: checkout
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Clear npm cache
      run: npm cache clean --force
      working-directory: ${{ github.workspace }}
      
    - name: Install dependencies
      run: npm install
      working-directory: ${{ github.workspace }}
      
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Run the tests
      run: npm test
      working-directory: /home/runner/work/1SCJR-fiap-notes/1SCJR-fiap-notes/
      
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Build
      run: npm run build --if-present
      working-directory: /home/runner/work/1SCJR-fiap-notes/1SCJR-fiap-notes/
      
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      working-directory: /home/runner/work/1SCJR-fiap-notes/1SCJR-fiap-notes/
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
